#!/bin/bash
cd $HOME \
&& sudo pacman --noconfirm -S \
 docker \
 docker-compose \
 postgresql \
 nginx \
 php-fpm \
 phppgadmin \
&& sudo -u postgres -i initdb --locale $LANG -E UTF8 -D /var/lib/postgres/data \
&& sudo systemctl enable postgresql \
&& sudo systemctl enable nginx \
&& sudo systemctl enable php-fpm \
&& yay --answerdiff=None --noconfirm -S \
 visual-studio-code-bin \
 mongodb-bin \
 mongodb-compass \
&& sudo systemctl enable mongodb \
&& cd $HOME/arch_conf \
&& sudo cp /etc/nginx/nginx.conf /etc/nginx/nginx.conf.bkp \
&& sudo cp server/nginx.conf /etc/nginx/ \
&& sudo cp /etc/php/php.ini /etc/php/php.ini.bkp \
&& sudo cp server/php.ini /etc/php/php.ini \
&& sudo ln -s /usr/share/webapps/phppgadmin /usr/share/nginx/html
