#!/bin/bash
cd $HOME \
&& sudo pacman --noconfirm -S \
 xorg \
 xorg-server \
 xorg-xinit \
 xorg-xbacklight \
 xorg-xprop \
 alsa-utils \
 volumeicon \
 dmenu \
 xterm \
 htop \
 slock \
 network-manager-applet \
 bash-completion \
 picom \
 dunst \
 ranger \
 sxiv \
 scrot \
 nitrogen \
 arandr \
 firefox \
 baobab \
 mlocate \
 neofetch \
 zathura \
 pcmanfm \
 noto-fonts \
 ttf-bitstream-vera \
 ttf-droid \
 ttf-linux-libertine \
 ttf-inconsolata \
 ttf-liberation \
 man \
 openssh \
 python-pip \
&& sudo pip3 install ueberzug \
&& sudo systemctl enable sshd \
&& git clone https://aur.archlinux.org/yay.git \
&& cd yay \
&& makepkg -si \
&& yay --answerdiff=None --noconfirm -S google-chrome \
 rxvt-unicode-pixbuf \
&& yay urxvt-perls \
&& cd $HOME/arch_conf \
&& cp -r home/. ~/ \
&& sudo cp neofetch_service.service /etc/systemd/system/ \
&& sudo systemctl --now enable neofetch_service.service \
&& mkdir ~/Pictures \
&& cp -R scripts $HOME/ \
&& chmod +x $HOME/scripts/* \
&& cp ws_Red_Autumn_1920x1080.jpg.c764983446194cba679411df337085b9.jpg ~/Pictures

